apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sietch-scraper
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: ../../infrastructure/sietch-scraper
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/yourusername/sietch-scraper  # Update this
      tag: latest
    
    postgresql:
      enabled: true
      auth:
        database: sietch_tracker
        username: postgres
        existingSecret: sietch-scraper-db-credentials
      primary:
        persistence:
          enabled: true
          size: 1Gi
          storageClass: local-path  # Update this based on your cluster

    scraper:
      interval: 300
      database:
        host: sietch-scraper-postgresql
        port: "5432"
        name: sietch_tracker
        user: postgres
        existingSecret: sietch-scraper-db-credentials
        existingSecretPasswordKey: password 