apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname
  namespace: monitoring
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: "homelab-kv"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: grafana-admin-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: acr-username
          objectType: secret
          objectVersion: ""
        - |
          objectName: acr-password
          objectType: secret
          objectVersion: ""
  secretObjects:
    - data:
        - key: admin-password
          objectName: grafana-admin-password
      secretName: grafana-secret
      type: Opaque
    - data:
        - key: username
          objectName: acr-username
        - key: password
          objectName: acr-password
      secretName: acr-credentials
      type: Opaque 