---
- name: Install HAProxy prerequisites
  package:
    name:
      - software-properties-common
      - ca-certificates
      - apt-transport-https
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Add HAProxy repository (Ubuntu)
  apt_repository:
    repo: ppa:vbernat/haproxy-3.0
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install HAProxy and required packages
  package:
    name:
      - haproxy
      - curl
      - jq
      - openssl
      - netcat-openbsd
    state: present
  tags:
    - haproxy_install
    - haproxy_config
    - ssl_config
    - config_update
    - always

# Note: Let's Encrypt/certbot packages removed - using Cloudflare Origin certificates

- name: Ensure HAProxy configuration directory exists
  file:
    path: /etc/haproxy
    state: directory
    mode: '0755'

- name: Ensure HAProxy certificate directory exists
  file:
    path: /etc/haproxy/certs
    state: directory
    mode: '0700'
    owner: root
    group: root