apiVersion: batch/v1
kind: Job
metadata:
  name: grafana-admin-secret-generator
  namespace: monitoring
  annotations:
    sidecar.istio.io/inject: "false"  # Disable Istio sidecar injection
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"  # Disable Istio sidecar injection
    spec:
      serviceAccountName: grafana-secret-generator
      containers:
      - name: secret-generator
        image: bitnami/kubectl:latest
        command:
        - /bin/bash
        - -c
        - |
          set -e
          # Check if secret already exists
          if kubectl get secret grafana-secret -n monitoring &> /dev/null; then
            echo "Secret grafana-secret already exists, skipping creation"
            exit 0
          fi

          # Generate a secure admin password
          ADMIN_PASSWORD=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-32)

          # Create the admin secret with validation disabled due to API server issue
          if kubectl create secret generic grafana-secret \
            --namespace=monitoring \
            --from-literal=admin_password="$ADMIN_PASSWORD" \
            --validate=false; then
            echo "Grafana admin secret generated successfully"
            echo "Admin password: $ADMIN_PASSWORD"
          else
            echo "Failed to create secret"
            exit 1
          fi
      restartPolicy: OnFailure