apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-generator
  namespace: monitoring
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "update", "patch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-generator
  namespace: monitoring
subjects:
- kind: ServiceAccount
  name: grafana-secret-generator
  namespace: monitoring
roleRef:
  kind: Role
  name: secret-generator
  apiGroup: rbac.authorization.k8s.io
