apiVersion: v1
kind: Secret
metadata:
  name: grafana-oauth-secret
  namespace: monitoring
type: Opaque
stringData:
  client_id: "${AUTHENTIK_CLIENT_ID}"
  client_secret: "${AUTHENTIK_CLIENT_SECRET}"
