apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
# Kubernetes API and core resources
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - nodes/metrics
  - services
  - endpoints
  - pods
  - namespaces
  - configmaps
  verbs: ["get", "list", "watch"]

# Extensions and networking
- apiGroups: 
  - "extensions"
  - "networking.k8s.io"
  resources:
  - ingresses
  - servicemonitors
  verbs: ["get", "list", "watch"]

# Apps resources (for deployments, statefulsets, etc.)
- apiGroups: ["apps"]
  resources:
  - deployments
  - daemonsets
  - statefulsets
  - replicasets
  verbs: ["get", "list", "watch"]

# Batch resources (for jobs, cronjobs)
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["get", "list", "watch"]

# Custom metrics
- apiGroups: ["monitoring.coreos.com"]
  resources:
  - servicemonitors
  - podmonitors
  - prometheusrules
  verbs: ["get", "list", "watch"]

# Istio metrics
- apiGroups: [""]
  resources:
  - services/proxy
  verbs: ["get"]

# Non-resource URLs (metrics endpoints)
- nonResourceURLs: 
  - "/metrics"
  - "/federate"
  - "/ready"
  - "/healthz"
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: monitoring