replicaCount: 1

image:
  repository: your-acr-name.azurecr.io/sietch-scraper  # Update this with your ACR name
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: acr-secret  # Will be created by Azure DevOps pipeline
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Scraper configuration
scraper:
  # Scraping interval in seconds
  interval: 300
  
  # Database configuration
  database:
    host: "postgresql"
    port: "5432"
    name: "sietch_tracker"
    user: "postgres"
    existingSecret: "sietch-scraper-db-credentials"
    existingSecretPasswordKey: "password"

# Configure PostgreSQL dependency
postgresql:
  enabled: true
  auth:
    database: sietch_tracker
    username: postgres
    existingSecret: "sietch-scraper-db-credentials"
  primary:
    persistence:
      enabled: true
      size: 1Gi
      storageClass: "local-path"  # Update this based on your cluster's storage class 