apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-subdir-external-provisioner
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nfs-subdir-external-provisioner-runner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nfs-subdir-external-provisioner-runner
subjects:
  - kind: ServiceAccount
    name: nfs-subdir-external-provisioner
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: nfs-subdir-external-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-subdir-external-provisioner
  namespace: kube-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-subdir-external-provisioner
  template:
    metadata:
      labels:
        app: nfs-subdir-external-provisioner
    spec:
      serviceAccountName: nfs-subdir-external-provisioner
      containers:
        - name: nfs-subdir-external-provisioner
          image: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: configs
              mountPath: /mnt/Flash/Configs
            - name: vault-data
              mountPath: /mnt/Vault/Data
            - name: influxdb-data
              mountPath: /mnt/Vault/Data/InfluxDB
            - name: etcd-data
              mountPath: /mnt/Vault/Data/etcd
            - name: monitoring-data
              mountPath: /mnt/Vault/Data/monitoring-data
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: PROVISIONER_NAME
              value: k8s-sigs.io/nfs-subdir-external-provisioner
            - name: NFS_SERVER
              value: "192.168.103.114"
            - name: NFS_PATH
              value: "/mnt/Vault/Data"
      volumes:
        - name: configs
          nfs:
            server: 192.168.103.114
            path: /mnt/Flash/Configs
        - name: vault-data
          nfs:
            server: 192.168.103.114
            path: /mnt/Vault/Data
        - name: influxdb-data
          nfs:
            server: 192.168.103.114
            path: /mnt/Vault/Data/InfluxDB
        - name: etcd-data
          nfs:
            server: 192.168.103.114
            path: /mnt/Vault/Data/etcd
        - name: monitoring-data
          nfs:
            server: 192.168.103.114
            path: /mnt/Vault/Data/monitoring-data