# NFS Storage Classes and PersistentVolumes
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vault-data-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.103.114
  share: /mnt/Vault/Data
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: influxdb-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.103.114
  share: /mnt/Vault/Data/InfluxDB
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: etcd-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.103.114
  share: /mnt/Vault/Data/etcd
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: flash-configs-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.103.114
  share: /mnt/Flash/Configs
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: monitoring-data-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.103.114
  share: /mnt/Vault/Data/monitoring-data
mountOptions:
  - nfsvers=4.1
  - hard
  - noatime
reclaimPolicy: Retain
volumeBindingMode: Immediate