apiVersion: batch/v1
kind: Job
metadata:
  name: influxdb-secret-generator
  namespace: database
  annotations:
    sidecar.istio.io/inject: "false"  # Disable Istio sidecar injection
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"  # Disable Istio sidecar injection
    spec:
      serviceAccountName: database-secret-generator
      containers:
      - name: secret-generator
        image: bitnami/kubectl:latest
        command:
        - /bin/bash
        - -c
        - |
          set -e
          # Check if secret already exists
          if kubectl get secret influxdb-secret -n database &> /dev/null; then
            echo "Secret influxdb-secret already exists, skipping creation"
            exit 0
          fi

          # Generate secure credentials
          INFLUXDB_PASSWORD=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-32)
          ADMIN_TOKEN=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-32)

          # Create the secret
          if kubectl create secret generic influxdb-secret \
            --namespace=database \
            --from-literal=username="influxdb" \
            --from-literal=password="$INFLUXDB_PASSWORD" \
            --from-literal=admin_token="$ADMIN_TOKEN" \
            --validate=false; then
            echo "InfluxDB secret generated successfully"
            echo "Password: $INFLUXDB_PASSWORD"
            echo "Admin Token: $ADMIN_TOKEN"
          else
            echo "Failed to create secret"
            exit 1
          fi
      restartPolicy: OnFailure
