# PostgreSQL deployment for shared database services
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: database
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: password
        - name: PGDATA
          value: "/data/postgresql/pgdata"
        volumeMounts:
        - name: postgres-data
          mountPath: /data/postgresql
        - name: postgres-backup
          mountPath: /backup/postgresql
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - $(POSTGRES_USER)
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - $(POSTGRES_USER)
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgresql-data
      - name: postgres-backup
        persistentVolumeClaim:
          claimName: postgresql-backup
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: database
  labels:
    app: postgresql
spec:
  selector:
    app: postgresql
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: database
type: Opaque
stringData:
  username: "postgres"
  password: "your-strong-postgres-password"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vault-data-nfs
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-backup
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vault-data-nfs
  resources:
    requests:
      storage: 50Gi
