apiVersion: batch/v1
kind: Job
metadata:
  name: postgresql-secret-generator
  namespace: database
  annotations:
    sidecar.istio.io/inject: "false"  # Disable Istio sidecar injection
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"  # Disable Istio sidecar injection
    spec:
      serviceAccountName: database-secret-generator
      containers:
      - name: secret-generator
        image: bitnami/kubectl:latest
        command:
        - /bin/bash
        - -c
        - |
          set -e
          # Check if secret already exists
          if kubectl get secret postgresql-secret -n database &> /dev/null; then
            echo "Secret postgresql-secret already exists, skipping creation"
            exit 0
          fi

          # Generate secure password
          POSTGRES_PASSWORD=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-32)
          
          # Create connection URL for postgres-exporter
          POSTGRES_URL="postgresql://postgres:${POSTGRES_PASSWORD}@postgresql:5432/postgres?sslmode=disable"

          # Create the secret
          if kubectl create secret generic postgresql-secret \
            --namespace=database \
            --from-literal=password="$POSTGRES_PASSWORD" \
            --from-literal=url="$POSTGRES_URL" \
            --validate=false; then
            echo "PostgreSQL secret generated successfully"
            echo "Password: $POSTGRES_PASSWORD"
          else
            echo "Failed to create secret"
            exit 1
          fi
      restartPolicy: OnFailure
