apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
- postgresql
- prometheus
- grafana
- loki

commonLabels:
  app.kubernetes.io/part-of: monitoring-stack
