---
# File: Ansible\site.yml
- name: Setup NFS mounts
  hosts: kubernetes
  become: true
  roles:
    - role: nfs

- name: Initialize first control plane node
  hosts: rke2_servers[0]
  become: true
  vars:
    is_first_control_plane: true
  roles:
    - role: rke2

- name: Wait for first control plane to stabilize
  hosts: rke2_servers[0]
  become: true
  tasks:
    - name: Pause for 60 seconds
      pause:
        seconds: 60
      delegate_to: localhost

- name: Setup additional control plane nodes
  hosts: rke2_servers[1:]
  become: true
  vars:
    is_first_control_plane: false
  roles:
    - role: rke2

- name: Setup worker nodes
  hosts: rke2_agents
  become: true
  vars:
    is_first_control_plane: false
  roles:
    - role: rke2

- name: Bootstrap cluster services (after all nodes are ready)
  hosts: rke2_servers[0]
  become: true
  vars:
    is_first_control_plane: true
  tags:
    - bootstrap
  tasks:
    - name: Include bootstrap tasks
      include_tasks: roles/rke2/tasks/bootstrap.yml
      tags:
        - bootstrap
