---
# File: Ansible\roles\rke2\defaults\main.yml
rke2_version: "v1.28.8+rke2r1"
rke2_install_path: "/usr/local/bin"
rke2_config_path: "/etc/rancher/rke2"

kubernetes_version: "v1.28.8"

rke2_role: "server"  # Can be 'server' or 'agent'
rke2_server_url: "https://{{ ansible_host }}:6443"
node_labels:
  - "node.kubernetes.io/role=worker"  # Default label for worker nodes

rke2_max_pods: 110
rke2_system_reserved_cpu: "500m"
rke2_system_reserved_memory: "500Mi"
rke2_kube_reserved_cpu: "500m"
rke2_kube_reserved_memory: "500Mi"

rke2_config:
  "tls-san":
    - "{{ ansible_host }}"
    - "{{ inventory_hostname }}"
  node_ip: "{{ ansible_host }}"
  node_external_ip: "{{ ansible_host }}"
  disable: []
  cni: "calico"
  service_node_port_range: "30000-32767"
  cluster_cidr: "10.42.0.0/16"
  service_cidr: "10.43.0.0/16"
  cluster_dns: "10.43.0.10"
  cluster_domain: "cluster.local"
  write_kubeconfig_mode: "0644"

argocd_version: "latest"
argocd_namespace: "argocd"
argocd_values:
  server:
    service:
      type: NodePort
    ingress:
      enabled: false
  dex:
    enabled: false
  notifications:
    enabled: true 
