---
# File: Ansible\roles\rke2\defaults\main.yml
rke2_install_path: "/usr/local/bin"
rke2_config_path: "/etc/rancher/rke2"
rke2_max_pods: 110
rke2_system_reserved_cpu: "500m"
rke2_system_reserved_memory: "500Mi"
rke2_kube_reserved_cpu: "500m"
rke2_kube_reserved_memory: "500Mi"

rke2_config:
  "tls-san":
    - "{{ ansible_host }}"
    - "{{ inventory_hostname }}"
  node_ip: "{{ ansible_host }}"
  node_external_ip: "{{ ansible_host }}"
  disable: []
  cni: "calico"
  service_node_port_range: "30000-32767"
  write_kubeconfig_mode: "0644"