# HAProxy configuration variables
domain_name: "mrcurls.org"
additional_domains:
  - "*.mrcurls.org"

# Let's Encrypt configuration
letsencrypt_email: "mrcurls@mrcurls.org"
# DNS challenge propagation time (seconds)
dns_propagation_seconds: 120

# Network configuration
vlan_id: 2  # VLAN ID for HAProxy traffic
virtual_ip: "172.16.255.254"  # Virtual IP for HAProxy
virtual_ip_cidr: 16
default_gateway: "172.16.0.1"  # Default gateway IP
dns_servers: "172.16.0.1"  # DNS server is the gateway

# HAProxy stats settings
haproxy_stats_enabled: true
haproxy_stats_uri: "/haproxy-stats"
haproxy_stats_user: "admin"
haproxy_stats_password: "{{ vault_haproxy_stats_password }}"

# Prometheus exporters settings
haproxy_exporter_version: "0.13.0"
haproxy_exporter_port: 9101
haproxy_exporter_metrics_uri: /metrics
node_exporter_version: "1.3.1"
node_exporter_port: 9100

# High Availability settings
keepalived_interface: "eth0.{{ vlan_id }}"  # Use VLAN interface
keepalived_router_id: 51
keepalived_auth_pass: "{{ vault_keepalived_auth_pass }}"

# HAProxy version
haproxy_version: 2.6

# HAProxy global settings
haproxy_socket: /var/lib/haproxy/stats
haproxy_chroot: /var/lib/haproxy
haproxy_user: haproxy
haproxy_group: haproxy

# Haproxy exporter user and password
haproxy_exporter_user: metrics
haproxy_exporter_password: "{{ vault_haproxy_exporter_password }}"
