---
# File: Ansible\roles\rke2\tasks\main.yml
- name: Include common tasks
  include_tasks: common.yml

- name: Include server init tasks (first control plane)
  include_tasks: server_init.yml
  when: rke2_role == 'server' and (is_first_control_plane | default(false) | bool)

- name: Include server join tasks (additional control planes)
  include_tasks: server_join.yml
  when: rke2_role == 'server' and not (is_first_control_plane | default(false) | bool)

- name: Include agent tasks
  include_tasks: agent.yml
  when: rke2_role == 'agent'

- name: Include post-installation tasks
  include_tasks: post_install.yml
  when: rke2_role == 'server'
