---
# File: Ansible\roles\rke2\tasks\post_install.yml
- name: Debug node information
  debug:
    msg: >
      Node type: {{ rke2_role }}, 
      Hostname: {{ ansible_hostname }}, 
      Is first control plane: {{ is_first_control_plane | default(false) | bool }},
      Inventory name: {{ inventory_hostname }}

- name: Server node kubectl tasks
  when: rke2_role == 'server'
  block:
    - name: Add Kubernetes APT repository key
      apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
        keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        state: present

    - name: Add Kubernetes APT repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"
        state: present
        filename: kubernetes

    - name: Update APT cache after adding Kubernetes repository
      apt:
        update_cache: yes

    - name: Install kubectl via APT (most reliable method)
      apt:
        name: kubectl
        state: present
        force_apt_get: yes

    - name: Create kubectl completion
      shell: kubectl completion bash > /etc/bash_completion.d/kubectl
      args:
        creates: /etc/bash_completion.d/kubectl

    - name: Set up kubeconfig for users
      include_tasks: kube-config.yml
      loop:
        - { home: '/root', owner: 'root'}
        - { home: '/home/ansible', owner: 'ansible'}
      loop_control:
        loop_var: kube_user

- name: First control plane node tasks
  when: rke2_role == 'server' and is_first_control_plane | default(false) | bool
  block:
    - name: Create required namespaces
      kubernetes.core.k8s:
        name: "{{ item }}"
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: /etc/rancher/rke2/rke2.yaml
      with_items:
        - metallb-system
        - cattle-system
        - keda
        - cattle-monitoring-system
        - cert-manager
        - nfs-provisoners
        - external-dns
        - cattle-fleet-system
        # Note: istio-system and argocd namespaces created via bootstrap manifests
      register: namespace_result
      until: namespace_result is succeeded
      retries: 5
      delay: 10
      
    # Enhanced Helm Installation
    - name: Download helm
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '700'
      register: helm_download

    - name: Check if Helm is already installed
      ansible.builtin.command: helm version --short
      register: helm_check
      failed_when: false
      changed_when: false

    - name: Install Helm if not present
      ansible.builtin.command: /tmp/get_helm.sh
      when: helm_check.rc != 0
      register: helm_install
      retries: 3
      delay: 10

    - name: Remove Helm install script
      ansible.builtin.file:
        path: /tmp/get_helm.sh
        state: absent

    - name: Add required Helm repositories
      kubernetes.core.helm_repository:
        name: "{{ item.name }}"
        repo_url: "{{ item.url }}"
        state: present
        kubeconfig: /etc/rancher/rke2/rke2.yaml
      loop:
        - { name: 'jetstack', url: 'https://charts.jetstack.io' }
        - { name: 'rancher-stable', url: 'https://releases.rancher.com/server-charts/stable' }
        - { name: 'kedacore', url: 'https://kedacore.github.io/charts' }
        - { name: 'metallb', url: 'https://metallb.github.io/metallb' }
        - { name: 'argo', url: 'https://argoproj.github.io/argo-helm' }
        - { name: 'longhorn', url: 'https://charts.longhorn.io' }
        - { name: 'bitnami', url: 'https://charts.bitnami.com/bitnami' }
        - { name: 'istio', url: 'https://istio-release.storage.googleapis.com/charts' }
        - { name: 'nfs-subdir-external-provisioner', url: 'https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner' }
        - { name: 'external-dns', url: 'https://kubernetes-sigs.github.io/external-dns/'}
        - { name: 'rancher-charts', url: 'https://charts.rancher.io'}
      register: helm_repo_add

    - name: Check if Helm config exists for root
      ansible.builtin.stat:
        path: /root/.config/helm
      register: helm_config

    - name: Remove existing non-empty helm directory if it exists
      ansible.builtin.file:
        path: "/home/ansible/.config/helm"
        state: absent
      when: helm_config.stat.exists

    - name: Ensure destination directory exists for each user
      ansible.builtin.file:
        path: "/home/ansible/.config"
        state: directory
        owner: "ansible"
        group: "ansible"
        mode: '0777'
      when: helm_config.stat.exists

    - name: Symlink Helm config to user's home
      ansible.builtin.file:
        src: /root/.config/helm
        dest: "/home/ansible/.config/helm"
        state: link
        force: yes
      when: helm_config.stat.exists

    - name: Find all files in the helm config directory
      ansible.builtin.find:
        paths: "/home/ansible/.config/helm"
        recurse: yes
      register: helm_files
      become: true
      when: helm_config.stat.exists

    - name: Set correct permissions and ownership for files in the helm config directory
      ansible.builtin.file:
        path: "{{ item.path }}"
        owner: "ansible"
        group: "ansible"
        mode: '0775'
      with_items: "{{ helm_files.files }}"
      become: true
      when: helm_config.stat.exists and helm_files.files is defined

    - name: Update all Helm repos
      ansible.builtin.command: helm repo update
      environment:
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml
      register: helm_update

    # Note: ArgoCD installation removed - will be handled via manifest bootstrap
    
    # === KUBERNETES MANIFEST BOOTSTRAP ===
    # Copy essential manifests for Istio and ArgoCD bootstrap

    - name: Create kubernetes-bootstrap directory
      file:
        path: /opt/kubernetes-bootstrap
        state: directory
        owner: root
        group: root
        mode: '0755'
    
    - name: Create bootstrap manifests directory
      file:
        path: /opt/kubernetes-bootstrap/bootstrap
        state: directory
        owner: root
        group: root
        mode: '0755'
    
    - name: Create ArgoCD bootstrap directory
      file:
        path: /opt/kubernetes-bootstrap/bootstrap/argocd
        state: directory
        owner: root
        group: root
        mode: '0755'
    
    - name: Copy ArgoCD bootstrap manifests
      copy:
        src: "{{ item }}"
        dest: "/opt/kubernetes-bootstrap/bootstrap/argocd/"
        owner: root
        group: root
        mode: '0644'
      with_fileglob:
        - "{{ playbook_dir }}/../../kubernetes/argocd/bootstrap/*"
    
    - name: Create Istio bootstrap directory
      file:
        path: /opt/kubernetes-bootstrap/bootstrap/istio
        state: directory
        owner: root
        group: root
        mode: '0755'
    
    - name: Copy Istio infrastructure manifests
      copy:
        src: "{{ item }}"
        dest: "/opt/kubernetes-bootstrap/bootstrap/istio/"
        owner: root
        group: root
        mode: '0644'
      with_fileglob:
        - "{{ playbook_dir }}/../../kubernetes/infrastructure/istio/*"
        
    # Install NFS provisioners after NFS role has run
    - name: Install NFS provisioners
      kubernetes.core.helm:
        name: "nfs-{{ item.name }}"
        chart_ref: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
        release_namespace: nfs-provisoners
        values:
          nfs:
            server: "{{ nfs_server }}.{{ domain_name }}"
            path: "{{ item.path }}"
          storageClass:
            name: "{{ item.Storage_class }}"
            defaultClass: false
            reclaimPolicy: Retain
        state: present
        kubeconfig: /etc/rancher/rke2/rke2.yaml
      loop: "{{ nfs_provisioners }}"
      when: nfs_role_completed | default(false) | bool
      register: nfs_provisioner_install
      retries: 5
      delay: 10
      until: nfs_provisioner_install is succeeded 
