---
# File: Ansible\roles\rke2\tasks\server_join.yml

- name: Download RKE2 installation script
  get_url:
    url: https://get.rke2.io
    dest: /tmp/rke2-install.sh
    mode: '0755'

- name: Install RKE2 server
  command: /tmp/rke2-install.sh
  args:
    creates: "{{ rke2_install_path }}/rke2"
  environment:
    INSTALL_RKE2_VERSION: "{{ rke2_version }}"
    INSTALL_RKE2_TYPE: "server"

- name: Create RKE2 config directory
  file:
    path: "{{ rke2_config_path }}"
    state: directory
    mode: '0755'

- name: Configure RKE2 server (join)
  template:
    src: server_join_config.yaml.j2
    dest: "{{ rke2_config_path }}/config.yaml"
    mode: '0644'
  notify: restart rke2

- name: Enable and start RKE2 service
  systemd:
    name: rke2-server
    state: started
    enabled: yes
    daemon_reload: yes

- name: Wait for kubeconfig to be generated
  wait_for:
    path: /etc/rancher/rke2/rke2.yaml
    state: present
    timeout: 300

- name: Wait for kubectl to be installed and symlinked
  wait_for:
    path: /var/lib/rancher/rke2/bin/kubectl
    state: present
    timeout: 300

- name: Wait for RKE2 to be ready
  shell: "systemctl status rke2-server | grep 'Active:' | grep -q 'active (running)'"
  register: rke2_status
  until: rke2_status.rc == 0
  retries: 30
  delay: 10
  changed_when: false
  failed_when: false

- name: Check if RKE2 pods are running
  shell: "sudo /var/lib/rancher/rke2/bin/kubectl --kubeconfig=/etc/rancher/rke2/rke2.yaml get pods -A"
  register: kubectl_check
  until: kubectl_check.rc == 0
  retries: 30
  delay: 10
  changed_when: false
  failed_when: false 
