---
# File: Ansible\roles\nfs\defaults\main.yml
nfs_server: "{{ nfs_server | default('192.168.103.114') }}"

nfs_mount_options: "rw,noatime,vers=4"

# Longhorn storage mount point
longhorn_mount_point: /mnt/longhorn
longhorn_mount_mode: '0755'

nfs_provisioners:
  - name: vault-data
    path: /mnt/Vault/Data
    Storage_class: vault-data-nfs

  - name: backup
    path: /mnt/Vault/Backup
    Storage_class: backup-nfs
  
  - name: etcd
    path: /mnt/Vault/Data/etcd
    Storage_class: etcd-nfs
  
  - name: flash-configs
    path: /mnt/Flash/Configs
    Storage_class: flash-configs-nfs
  
  - name: monitoring-data
    path: /mnt/Vault/Data/monitoring-data
    Storage_class: monitoring-data-nfs

nfs_mounts:
  - path: /mnt/Vault/Data
    src: /mnt/Vault/Data

  - path: /mnt/Data/InfluxDB
    src: /mnt/Vault/Data/InfluxDB

  - path: /mnt/Data/etcd
    src: /mnt/Vault/Data/etcd

  - path: /mnt/Configs
    src: /mnt/Flash/Configs

  - path: /mnt/Data/Monitoring
    src: /mnt/Vault/Data/monitoring-data

  - path: /mnt/Data/Backup
    src: /mnt/Vault/Backup