apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: monitoring
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgresql
  selector:
    app: postgresql
  type: ClusterIP 