nfs_server: "truenas"
domain_name: "mrcurls.org"
rancher_bootstrap_password: "admin"
metallb_version: "v0.14.9"
rancher_version: "2.10.3"

nfs_provisioners:
  - name: vault-data
    path: /mnt/Vault/Data
    Storage_class: vault-data-nfs
  - name: influxdb
    path: /mnt/Vault/Data/InfluxDB
    Storage_class: influxdb-nfs
  - name: etcd
    path: /mnt/Vault/Data/Etcd
    Storage_class: etcd-nfs
  - name: flash-configs
    path: /mnt/Flash/Configs
    Storage_class: flash-configs-nfs
  - name: monitoring-data
    path: /mnt/Vault/Data/monitoring-data
    Storage_class: monitoring-data-nfs