nfs_server: "truenas"
domain_name: "mrcurls.org"
rancher_bootstrap_password: "admin"
metallb_version: "v0.14.9"
rancher_version: "2.10.3"

nfs_provisioners:
  - name: vault-data
    path: /mnt/Vault/Data
    Storage_class: vault-data-nfs

  - name: influxdb
    path: /mnt/Data/InfluxDB
    Storage_class: influxdb-nfs
  
  - name: etcd
    path: /mnt/Data/etcd
    Storage_class: etcd-nfs
  
  - name: flash-configs
    path: /mnt/Configs
    Storage_class: flash-configs-nfs
  
  - name: monitoring-data
    path: /mnt/Data/Monitoring
    Storage_class: monitoring-data-nfs

nfs_mounts:
  - path: /mnt/Vault/Data
    src: /mnt/Vault/Data

  - path: /mnt/Data/InfluxDB
    src: /mnt/Vault/Data/InfluxDB

  - path: /mnt/Data/etcd
    src: /mnt/Vault/Data/etcd

  - path: /mnt/Configs
    src: /mnt/Flash/Configs

  - path: /mnt/Data/Monitoring
    src: /mnt/Vault/Data/monitoring-data