---
# File: Ansible\group_vars\all.yml
ansible_user: ubuntu
ansible_become: true
ansible_become_method: sudo

domain_name: "mrcurls.org"

rke2_version: "v1.28.8+rke2r1"
kubernetes_version: "v1.28.8"
metallb_version: "v0.14.9"
cert_manager_version: "v1.17.0"

helm_users:
  - ansible
  - root

cluster_cidr: "10.42.0.0/16"
service_cidr: "10.43.0.0/16"
cluster_dns: "10.43.0.10"
cluster_domain: "cluster.local"

nfs_server: "truenas"
nfs_provisioners:
  - name: vault-data
    path: /mnt/Vault/Data
    Storage_class: vault-data-nfs

  - name: influxdb
    path: /mnt/Vault/Data/InfluxDB
    Storage_class: influxdb-nfs
  
  - name: etcd
    path: /mnt/Vault/Data/etcd
    Storage_class: etcd-nfs
  
  - name: flash-configs
    path: /mnt/Flash/Configs
    Storage_class: flash-configs-nfs
  
  - name: monitoring-data
    path: /mnt/Vault/Data/monitoring-data
    Storage_class: monitoring-data-nfs

nfs_mounts:
  - path: /mnt/Vault/Data
    src: /mnt/Vault/Data

  - path: /mnt/Data/InfluxDB
    src: /mnt/Vault/Data/InfluxDB

  - path: /mnt/Data/etcd
    src: /mnt/Vault/Data/etcd

  - path: /mnt/Configs
    src: /mnt/Flash/Configs

  - path: /mnt/Data/Monitoring
    src: /mnt/Vault/Data/monitoring-data

rancher_bootstrap_password: "admin"

argocd_version: "latest"
argocd_namespace: "argocd"
argocd_values:
  server:
    service:
      type: NodePort
    ingress:
      enabled: true
      hosts:
        - argocd.{{ domain_name }}
      tls: true
  dex:
    enabled: false
  notifications:
    enabled: true 
