---
# File: Ansible\roles\nfs\tasks\main.yml
- name: Wait for apt lock to be released
  shell: while lsof /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 5; done
  changed_when: false
  timeout: 300
  when: ansible_os_family == 'Debian'

- name: Install NFS client packages
  apt:
    name:
      - nfs-common
      - nfs4-acl-tools
    state: present
    update_cache: yes
  ignore_errors: yes

- name: Create NFS mount points
  file:
    path: "{{ item.path }}"
    state: directory
    mode: '0755'
  with_items: "{{ nfs_mounts }}"

- name: Create Longhorn storage mount point
  file:
    path: "{{ longhorn_mount_point }}"
    state: directory
    mode: "{{ longhorn_mount_mode }}"
  become: true

- name: Mount NFS shares
  mount:
    path: "{{ item.path }}"
    src: "{{ nfs_server }}:{{ item.src }}"
    fstype: nfs4
    opts: "{{ nfs_mount_options | default('rw,noatime,vers=4') }}"
    state: mounted
  with_items: "{{ nfs_mounts }}"
  notify: restart nfs-client

- name: Include database backup tasks
  include_tasks: database_backup.yml