# Cloudflare cluster issuer for wildcard certificate generation
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mrcurls@mrcurls.org
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
      selector:
        dnsNames:
        - '*.mrcurls.org'
        - 'mrcurls.org'
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-mrcurls-net
  namespace: istio-system
spec:
  secretName: wildcard-mrcurls-net-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - '*.mrcurls.org'
  - 'mrcurls.org'
