- name: Install Kubectl on Masters
  command: >
    snap install kubectl --classic
  when: ansible_hostname in groups['k8s-master']
  register: kubectl_master

- name: Ensure Kube Config Directory is reset and updated
  include_tasks: kube_config.yml
  loop:
    - { home: '/root', owner: 'root'}
    - { home: '/home/{{ ansible_ssh_user }}', owner: "{{ ansible_ssh_user }}"}
  loop_control:
    loop_var: kube_user
  when: ansible_hostname in groups['k8s-master']

- name: Check Nodes
  command: >
    kubectl get nodes
  when: ansible_hostname in groups['k8s-master']
  register: nodes_master
  ignore_errors: true

- name: Debug Node Check
  debug:
    msg: "Node check output: {{ nodes_master.stdout }}"
  when: ansible_hostname in groups['k8s-master']

- name: Create Namespaces
  command: >
    kubectl create namespace {{ item }}
  loop:
    - istio-system
    - cert-manager
    - metallb-system
    - argocd
    - cattle-system
    - keda
  when: ansible_hostname in groups['k8s-master']
  register: create_namespace_master