- name: Install Kubectl on Masters
  community.general.snap:
    name: kubectl
    classic: yes
    state: present
  when: ansible_hostname in groups['k8smaster']
  register: kubectl_master
  retries: 3
  delay: 10
  timeout: 45

- name: Ensure Kube Config Directory is reset and updated
  include_tasks: kube-config.yml
  loop:
    - { home: '/root', owner: 'root'}
    - { home: '/home/{{ ansible_ssh_user }}', owner: "{{ ansible_ssh_user }}"}
  loop_control:
    loop_var: kube_user
  when: ansible_hostname in groups['k8smaster']

- name: Check Nodes
  kubernetes.core.k8s_info:
    kind: Node
  when: ansible_hostname in groups['k8smaster']
  register: nodes_master
  ignore_errors: true

- name: Extract specific node information
  debug:
    msg: "{{ nodes_master.resources | selectattr('metadata.name', 'equalto', 'node-name') | list }}"
  when: 
    - ansible_hostname in groups['k8smaster']
    - nodes_master is defined
    - nodes_master.resources is defined

- name: Create Namespaces
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ item }}"
  loop:
    - istio-system
    - metallb-system
    - argocd
    - cattle-system
    - keda
    - cattle-monitoring-system
    - cert-manager
    - nfs-provisoners
    - external-dns
  when: ansible_hostname == 'k8s-master-0'
  register: create_namespace_master

- name: Copy Mainfests
  copy:
    src: "{{ playbook_dir }}/k8smanifests"
    dest: "/tmp/k8smanifests"
  when: ansible_hostname == 'k8s-master-0'

- name: Find all files in the helm config directory
  ansible.builtin.find:
    paths: "/tmp/k8smanifests"
    recurse: yes
  register: manifest_files
  become: true
  when: ansible_hostname == 'k8s-master-0'

- name: Set correct permissions and ownership for files in the helm config directory
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: ansible
    group: ansible
    mode: '0775'
  with_items: "{{ manifest_files.files }}"
  become: true
  when: ansible_hostname == 'k8s-master-0'

- name: Download Metallb manifest
  get_url:
    url: "https://raw.githubusercontent.com/metallb/metallb/{{ metallb_version }}/config/manifests/metallb-native.yaml"
    dest: "/tmp/metallb-native.yaml"
  when: ansible_hostname == 'k8s-master-0'

- name: Apply Metallb manifest
  kubernetes.core.k8s:
    state: present
    src: "/tmp/metallb-native.yaml"
  when: ansible_hostname == 'k8s-master-0'

- name: Apply Metallb Config from remote file
  kubernetes.core.k8s:
    state: present
    src: "/tmp/metallb-config.yaml"
  when: ansible_hostname == 'k8s-master-0'
  register: metallb_config
  retries: 10
  delay: 10

- name: Clean up Metallb config file
  ansible.builtin.file:
    path: /tmp/metallb-config.yaml
    state: absent
  when: ansible_hostname == 'k8s-master-0'

- name: Check if the CRD for gateway exists
  kubernetes.core.k8s_info:
    kind: CustomerResourceDefinition
    name: gateways.gateway.networking.k8s.io
  register: crd_check
  ignore_errors: true
  when: ansible_hostname == 'k8s-master-0'

- name: Download the CRD YAML
  get_url:
    url: "https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.1/standard-install.yaml"
    dest: /tmp/standard-install.yaml
    mode: '0755'
  register: crd_yaml
  when: ansible_hostname == 'k8s-master-0' and crd_check.failed

- name: Apply CRD
  ansible.builtin.k8s:
    state: present
    definition: "{{ lookup ('file'. '/tmp/standard-install.yaml') | from_yaml }}"
  when: ansible_hostname == 'k8s-master-0' and crd_check.failed
  become: true