apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: PostgreSQL
      type: postgres
      url: postgresql:5432
      database: monitoring
      user: $POSTGRES_USER
      secureJsonData:
        password: $POSTGRES_PASSWORD
      jsonData:
        sslmode: "disable"
        maxOpenConns: 100
        maxIdleConns: 100
        connMaxLifetime: 14400
        postgresVersion: 1600
        timescaledb: false
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus:9090
      isDefault: true
    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3100
      isDefault: false 