apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- configmap.yaml

secretGenerator:
- name: grafana-secret
  namespace: monitoring
  literals:
  - admin-password=change-me-in-vault

commonLabels:
  app.kubernetes.io/component: grafana
