# Istio gateway for ingress traffic routing
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: main-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*.mrcurls.org"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argocd-vs
  namespace: argocd
spec:
  hosts:
  - argocd.mrcurls.org
  gateways:
  - istio-system/main-gateway
  http:
  - match:
    - uri:
        exact: /
    redirect:
      uri: /applications
  - match:
    - uri:
        prefix: /
    headers:
      request:
        set:
          x-forwarded-proto: https
          x-forwarded-host: argocd.mrcurls.org
          x-forwarded-port: "443"
    corsPolicy:
      allowHeaders:
      - "*"
      allowMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
      allowOrigins:
      - exact: https://argocd.mrcurls.org
      maxAge: "24h"
    route:
    - destination:
        host: argocd-server
        port:
          number: 80
