apiVersion: v1
kind: ServiceAccount
metadata:
  name: authentik-secret-generator
  namespace: auth
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: authentik-secret-generator
  namespace: auth
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "update", "patch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: authentik-secret-generator
  namespace: auth
subjects:
- kind: ServiceAccount
  name: authentik-secret-generator
  namespace: auth
roleRef:
  kind: Role
  name: authentik-secret-generator
  apiGroup: rbac.authorization.k8s.io