# FlareSolverr deployment for Cloudflare bypass
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  namespace: servarr
  labels:
    app: flaresolverr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaresolverr
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      containers:
      - name: flaresolverr
        image: ghcr.io/flaresolverr/flaresolverr:latest
        ports:
        - containerPort: 8191
        - containerPort: 8192
          name: prometheus
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Chicago"
        - name: LOG_LEVEL
          value: "info"
        - name: PROMETHEUS_ENABLED
          value: "true"
        - name: PROMETHEUS_PORT
          value: "8192"
        volumeMounts:
        - name: config
          mountPath: /config/flaresolverr
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
          requests:
            cpu: 150m
            memory: 128Mi
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: flaresolverr-config
---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  namespace: servarr
  labels:
    app: flaresolverr
spec:
  selector:
    app: flaresolverr
  ports:
  - name: http
    port: 8191
    targetPort: 8191
  - name: prometheus
    port: 8192
    targetPort: 8192
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flaresolverr-config
  namespace: servarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: flash-configs-nfs
  resources:
    requests:
      storage: 1Gi