apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  namespace: servarr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media-nfs
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies
  namespace: servarr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media-nfs
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tv
  namespace: servarr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media-nfs
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music
  namespace: servarr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media-nfs
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi