# Sonarr deployment for TV show management
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: servarr
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8989"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: sonarr
        image: lscr.io/linuxserver/sonarr:latest
        ports:
        - containerPort: 8989
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Chicago"
        volumeMounts:
        - name: config
          mountPath: /config/sonarr
        - name: downloads
          mountPath: /downloads
        - name: tv
          mountPath: /tv
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: sonarr-config
      - name: downloads
        persistentVolumeClaim:
          claimName: shared-downloads
      - name: tv
        persistentVolumeClaim:
          claimName: shared-tv
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: servarr
  labels:
    app: sonarr
spec:
  selector:
    app: sonarr
  ports:
  - name: http
    port: 8989
    targetPort: 8989
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: servarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: flash-configs-nfs
  resources:
    requests:
      storage: 5Gi
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sonarr-vs
  namespace: servarr
spec:
  hosts:
  - sonarr.mrcurls.org
  gateways:
  - istio-system/main-gateway
  http:
  - route:
    - destination:
        host: sonarr
        port:
          number: 8989
