- name: Install cert-manager using Helm
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    chart_version: "{{ cert_manager_version }}"
    release_namespace: cert-manager
    values:
      installCRDs: true
  register: cm_deploy
  retries: 2
  delay: 10
  until: cm_deploy is succeeded
  when: ansible_hostname == 'k8s-master-0'

- name: Apply Certmanager
  kubernetes.core.k8s:
    state: present
    src: "/tmp/k8smanifests/certmanager.yaml"
  when: ansible_hostname == 'k8s-master-0'
  register: certmanager_apply