apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
- deployment.yaml
- rbac.yaml
- storageclass.yaml

patchesStrategicMerge:
- overlays/nfs-config.yaml

commonLabels:
  app.kubernetes.io/part-of: storage-infrastructure
  app.kubernetes.io/component: nfs-provisioner
