---
apiVersion: v1
kind: Service
metadata:
  name: radarr-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: radarr-exporter
    app.kubernetes.io/instance: radarr-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9707"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app.kubernetes.io/name: radarr-exporter
    app.kubernetes.io/instance: radarr-exporter
  ports:
    - name: monitoring
      port: 9707
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: radarr-exporter
    app.kubernetes.io/instance: radarr-exporter
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr-exporter
      app.kubernetes.io/instance: radarr-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: radarr-exporter
        app.kubernetes.io/instance: radarr-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9707"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: servarr-exporter
      initContainers:
        - name: wait-for-secret
          image: bitnami/kubectl:latest
          command: ['sh', '-c', 'until kubectl get secret servarr-secret -n monitoring; do echo waiting for secret; sleep 2; done']
      containers:
        - name: radarr-exporter
          image: ghcr.io/onedr0p/exportarr:v1.5.3
          imagePullPolicy: IfNotPresent
          args:
            - radarr
          env:
            - name: PORT
              value: "9707"
            - name: URL
              value: "http://radarr.servarr.svc.cluster.local:7878"
            - name: APIKEY
              valueFrom:
                secretKeyRef:
                  name: servarr-secret
                  key: radarr_apikey
          ports:
            - name: monitoring
              containerPort: 9707
          livenessProbe:
            httpGet:
              path: /healthz
              port: monitoring
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: monitoring
            failureThreshold: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi